### ISSUE TITLE
JwtClaim validate method compares UTC and non-UTC times

### ISSUE THREAD

**Issue by adamlofts** [Jaguar-dart/jaguar_jwt#6]
This line is verifying the expiry of the token.

https://github.com/Jaguar-dart/jaguar_jwt/blob/cc2f149d5f24d5f9ed4eb068d7c225c86d71163a/lib/src/jaguar_jwt.dart#L137

`new DateTime.now()` is in local time
`expiry` is UTC

**Comment by tejainece** [comment]
Should be fixed by https://github.com/Jaguar-dart/jaguar_jwt/commit/60f1c76bbe8c9410b37e6fbd9f74a1e4fa2520af

**Comment by tejainece** [comment]
And by https://github.com/Jaguar-dart/jaguar_jwt/commit/f9192a278efaa93e19f15c60466d1921f9c5b5d8
