### ISSUE TITLE
JWT exp field

### ISSUE THREAD

**Issue by adamlofts** [Jaguar-dart/jaguar_jwt#7]
According to the specification the `exp` field is a NumericDate format (seconds since epoch). https://en.wikipedia.org/wiki/JSON_Web_Token

I think the code assumes it is an offset from the `iat` field.

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_jwt/commit/aafc83a5cb5ce53a5e3f7c88b193c4c6f09f4824
